---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: confluent-trigger-authentication
spec:
  secretTargetRef:
    - parameter: username
      key: CONFLUENT_API_KEY
      name: confluent-cloud-credentials-sasl

    - parameter: password
      key: CONFLUENT_API_SECRET
      name: confluent-cloud-credentials-sasl
