logging:
  level:
    org.springframework:
      kafka: INFO
      integration: INFO

spring:
  application:
    name: spring-integration-kafka

  kafka:
    enabled: true
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"

    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${SPRING_KAFKA_USERNAME}' password='${SPRING_KAFKA_PASSWORD}';
      session.timeout.ms: 45000

    consumer:
      topic: "${SPRING_KAFKA_CONSUMER_TOPIC:events-inbound}"
      client-id: "${SPRING_KAFKA_CONSUMER_CLIENT_ID:application-consumer}"
      group-id: "${SPRING_KAFKA_CONSUMER_GROUP_ID:consumers}"
      auto-offset-reset: "${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}"
      key-deserializer: com.github.smsilva.wasp.kafka.exceptions.ErrorHandlingDeserializerData
      value-deserializer: com.github.smsilva.wasp.kafka.exceptions.ErrorHandlingDeserializerData
      properties:
        spring.json.value.default.type: com.github.smsilva.wasp.kafka.entity.Data
        spring.json.type.mapping: "data:com.github.smsilva.wasp.kafka.entity.Data"
        spring.json.trusted.packages: "com.github.smsilva.*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.value.function: com.github.smsilva.wasp.kafka.exceptions.FailedDeserializationData

    producer:
      topic: "${KAFKA_TOPIC:events-outbound}"
      message-key: "${KAFKA_MESSAGE_KEY:events-inbound-key}"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: com.github.smsilva.wasp.kafka.entity.Data
        spring.json.type.mapping: "data:com.github.smsilva.wasp.kafka.entity.Data"
        spring.json.trusted.packages: "com.github.smsilva.*"
