spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  application:
    name: spring-integration-kafka

  kafka:
    enabled: true
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"

    consumer:
      topic: "${SPRING_KAFKA_CONSUMER_TOPIC:events-inbound}"
      client-id: "${SPRING_KAFKA_CONSUMER_CLIENT_ID:application-consumer}"
      group-id: "${SPRING_KAFKA_CONSUMER_GROUP_ID:consumers}"
      auto-offset-reset: "${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}"

    producer:
      topic: "${SPRING_KAFKA_PRODUCER_TOPIC:events-inbound}"
      message-key: "${SPRING_KAFKA_PRODUCER_MESSAGE_KEY:default-key}"

    simulation:
      seconds: ${SPRING_KAFKA_SIMULATION_SECONDS:0}

logging:
  level:
    org:
      springframework:
        kafka: INFO
        integration: INFO
        web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
