spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default,confluent}

  application:
    name: spring-integration-kafka

  kafka:
    enabled: true
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    consumer:
      topic: "${SPRING_KAFKA_CONSUMER_TOPIC:events-inbound}"
      client-id: "${SPRING_KAFKA_CONSUMER_CLIENT_ID:application-consumer}"
      group-id: "${SPRING_KAFKA_CONSUMER_GROUP_ID:consumers}"
      auto-offset-reset: "${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}"
      key-deserializer: com.github.smsilva.wasp.kafka.exceptions.ErrorHandlingDeserializerData
      value-deserializer: com.github.smsilva.wasp.kafka.exceptions.ErrorHandlingDeserializerData
      properties:
        spring.json.value.default.type: com.github.smsilva.wasp.kafka.entity.Data
        spring.json.type.mapping: "data:com.github.smsilva.wasp.kafka.entity.Data"
        spring.json.trusted.packages: "com.github.smsilva.*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.value.function: com.github.smsilva.wasp.kafka.exceptions.FailedDeserializationData

    producer:
      topic: "${SPRING_KAFKA_PRODUCER_TOPIC:events-outbound}"
      message-key: "${SPRING_KAFKA_PRODUCER_MESSAGE_KEY:events-inbound-key}"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: com.github.smsilva.wasp.kafka.entity.Data
        spring.json.type.mapping: "data:com.github.smsilva.wasp.kafka.entity.Data"
        spring.json.trusted.packages: "com.github.smsilva.*"

    simulation:
      seconds: ${SPRING_KAFKA_SIMULATION_SECONDS:0}

logging:
  level:
    org.springframework:
      kafka: INFO
      integration: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
