---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kakfa
spec:
  selector:
    app: kakfa

  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092

    - name: external
      port: 9094
      protocol: TCP
      targetPort: 9094

    - name: broker
      port: 19092
      protocol: TCP
      targetPort: 19092
